package cn.elonzh.hanppie.ui.chat

/** Longest title a conversation gets from its first message. */
internal const val MAX_SESSION_TITLE_LENGTH = 24

/**
 * The conversation title: the first message, flattened to a single line so the list row stays one line.
 * Titles are never generated by the model.
 */
internal fun sessionTitleFromMessage(message: String): String = message
    .lineSequence()
    .map(String::trim)
    .filter(String::isNotEmpty)
    .joinToString(" ")
    .take(MAX_SESSION_TITLE_LENGTH)
